export { StudentNavbar } from "./nav";
export { StudentRegister } from "./register";
export { StudentProfile } from "./dashboard";
export { StudentAppliedJobs } from "./appliedJobs";
export { StudentEligibleJobs } from "./eligibleJobs";
export { StudentAllJobs } from "./allJobs";
export { StudentRequests } from "./requests";
export { StudentResume } from "./resume";
export { StudentEditProfile} from "./editProfile";
export {StudentEditCPI} from "./editCPI";
